# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crs-namespace
type: Opaque
data:
  POSTGRES_DB: Y3JzX2Ri # base64 encoded 'crs_db'
  POSTGRES_USER: Y3JzX3VzZXI= # base64 encoded 'crs_user'
  POSTGRES_PASSWORD: Q3JzQDU0MzIx # base64 encoded 'password'
